// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnq0_9lZUaeawCElnWLZkuOZyRSrKp6uA',
    appId: '1:653535312276:web:814b9a4e6430226a9eb781',
    messagingSenderId: '653535312276',
    projectId: 'zaffari-automatic-feeder-dev',
    authDomain: 'zaffari-automatic-feeder-dev.firebaseapp.com',
    databaseURL: 'https://zaffari-automatic-feeder-dev-default-rtdb.firebaseio.com',
    storageBucket: 'zaffari-automatic-feeder-dev.appspot.com',
    measurementId: 'G-CJVZGVYN64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE84cZyCwvIE9QZVQci3Mr0dIljZbFqhY',
    appId: '1:653535312276:android:ae3d92ecda807d999eb781',
    messagingSenderId: '653535312276',
    projectId: 'zaffari-automatic-feeder-dev',
    databaseURL: 'https://zaffari-automatic-feeder-dev-default-rtdb.firebaseio.com',
    storageBucket: 'zaffari-automatic-feeder-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAutaqr642hoPzhrvvUTzjq7-SQ8KWYY_k',
    appId: '1:653535312276:ios:3280398b8dcec8219eb781',
    messagingSenderId: '653535312276',
    projectId: 'zaffari-automatic-feeder-dev',
    databaseURL: 'https://zaffari-automatic-feeder-dev-default-rtdb.firebaseio.com',
    storageBucket: 'zaffari-automatic-feeder-dev.appspot.com',
    iosBundleId: 'com.example.flutterAutomaticFeeder',
  );
}
